name: connect_ips_flutter
description: "Unofficial plugin for integrating connect ips gateway via flutter"
version: 1.0.0+3
issue_tracker: https://github.com/Ashwin1002/ConnectIPS-Flutter/issues
homepage: https://github.com/Ashwin1002/ConnectIPS-Flutter
repository: https://github.com/Ashwin1002/ConnectIPS-Flutter

screenshots:
  - description: "Connect IPS gateway"
    path: screenshots/payment.PNG

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.16.0"

platforms:
  android:
  ios:

dependencies:
  asn1lib: ^1.5.5
  crypto: ^3.0.6
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.1.5
  flutter_svg: ^2.0.10+1
  http: ^1.2.2
  internet_connection_checker: ^1.0.0+1
  intl: ^0.19.0
  pointycastle: ^3.9.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - LICENSE
