name: connect_ips_flutter
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  asn1lib: ^1.5.5
  crypto: ^3.0.6
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.1.5
  http: ^1.2.2
  internet_connection_checker_plus: ^2.5.2
  intl: ^0.19.0
  pointycastle: ^3.9.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    # insert your .pfx file in the asset and place the path
    # extract your pfx file using the following command:
    # ```openssl pkcs12 -in your_certificate.pfx -nocerts -nodes -out private_key.pem```
    - CREDITOR.pfx
    - private_key.pem
